### PR TITLE
Add resources icons and fix modal accessibility issue

### LINKED ISSUE #43: Modal compatibility with larger text
1. Bound the modal at max height < screen height
2. Wrap the inner contents of modal in ScrollView

Issue discovered in 
- Onboarding flow => “Don’t have an attorney?” 
- Emergency toolkit settings flow => “Edit” modal in Rights Card

Image from iOS (4)

### PR DESCRIPTION
**Pull request by knarangerel**
- Adds the new socials icons to the resources detail screen

- Resolves #43 (Modal overflow issue with larger text sizes) 

- Adds a scrollview to the emergency toolkit screen (the screen wasn't scrolling with larger text sizes) 

- Removed "Not over 13?" button on the welcome screen to match newer wireframes

icons

modal

scrollview

### CODE REVIEW

File: js/components/CustomModal.js [hunk 1]
```diff
@@ -26,25 +24,17 @@ const CustomModal = ({
...
-            <View style={styles.modalContainer}>
-              <View style={[styles.contentContainer, contentContainerStyle]}>
-                {children}
-                <PrimarySecondaryOptions
-                  primaryButton={primaryButton}
-                  secondaryButton={secondaryButton}
-                />
-              </View>
-            </View>
+      <View style={styles.modalContainer}>
```
Comment (kiwansim) [inline js/components/CustomModal.js:27]: Are we getting rid of` <TouchableWithoutFeedback onPress={Keyboard.dismiss}>` because we no longer have an input component in use that would trigger the keyboard to appear

Comment (knarangerel) [reply js/components/CustomModal.js:27]: TouchableWithoutFeedback just didn't work with a ScrollView (because you actually need to touch the screen to scroll). I figured it was fine to get rid of it for accessibility's sake because the modal close buttons are prominent and obvious on the screen.

Comment (knarangerel) [reply js/components/CustomModal.js:27]: So I went back and investigated and turns out you can still dismiss the keyboard by tapping outside. I think that just comes with KeyboardAvoidingView, and I have no clue what the TouchableWithoutFeedback was doing here in the first place.
I figured getting rid of parts related to the input component should be done later, and that's why KeyboardAvoidingView is still there.

Comment (kiwansim) [reply js/components/CustomModal.js:27]: Gotcha. This makes sense! Thanks for investigating
